---
# project-api Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-api
  template:
    metadata:
      labels:
        app: project-api
        dynatrace.com/pod-project-api-label: label-project-api-pod-value
        metadata.dynatrace.com/pod-project-api-label-metadata: label-project-api-pod-metadata-value
        metadata.dynatrace.com/deployment.release_stage: label-project-api-deployment-release-stage-value
        metadata.dynatrace.com/deployment.release_version: label-project-api-deployment-release-version-value
        pod-project-api-label: label-project-api-pod-value
        dynatrace.com/primary_tags.pod-project-api-label: label-project-api-pod-value
        metadata.dynatrace.com/primary_tags.pod-project-api-label-metadata: label-project-api-pod-metadata-value
        metadata.dynatrace.com/primary_tags.source: label-project-api-pod-value
        primary_tags.pod-label: label-project-api-pod-value
      annotations:
        dynatrace.com/pod-annotation: annotation-project-api-pod-value
        metadata.dynatrace.com/pod-annotation-metadata: annotation-project-api-pod-metadata-value
        metadata.dynatrace.com/deployment.release_stage: annotation-project-api-deployment-release-stage-value
        metadata.dynatrace.com/deployment.release_version: annotation-project-api-deployment-release-version-value
        pod-annotation: annotation-project-api-pod-value
        dynatrace.com/primary_tags.pod-annotation: annotation-project-api-pod-value
        metadata.dynatrace.com/primary_tags.pod-annotation-metadata: annotation-project-api-pod-metadata-value
        metadata.dynatrace.com/primary_tags.source: annotation-project-api-pod-value
        primary_tags.pod-annotation: annotation-project-api-pod-value
        metadata.dynatrace.com/primary_tags.dtmetavsdttags: dtmetadata
        metadata.dynatrace.com/primary_tags.hosttagvsdtmeta: dtmetadata
        metadata.dynatrace.com/primary_tags.dtmetavscentralcon: dtmetadata
        metadata.dynatrace.com/primary_tags.dttagsvsdtmetavscentralprocess: dtmetadata
    spec:
      containers:
        - name: project-api
          image: localhost:32000/test-applications-java:1.2.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: APP_PORT
              value: "5000"
            - name: APP_LOG_PATH
              value: /app/logs
          readinessProbe:
            httpGet:
              path: /api/projects
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/projects
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 30
          volumeMounts:
            - name: logs
              mountPath: /app/logs
      volumes:
        - name: logs
          emptyDir: {}
---
# project-api Service
apiVersion: v1
kind: Service
metadata:
  name: project-api
  labels:
    dynatrace.com/service-project-api-label: label-project-api-service-value
    metadata.dynatrace.com/service-project-api-label-metadata: label-project-api-service-metadata-value
    service-project-api-label: label-project-api-service-value
    dynatrace.com/primary_tags.service-project-api-label: label-project-api-service-value
    metadata.dynatrace.com/primary_tags.service-project-api-label-metadata: label-project-api-service-metadata-value
    metadata.dynatrace.com/primary_tags.source: label-project-api-service-value
    primary_tags.service-label: label-project-api-service-value
  annotations:
    dynatrace.com/service-annotation: annotation-project-api-service-value
    metadata.dynatrace.com/service-annotation-metadata: annotation-project-api-service-metadata-value
    service-annotation: annotation-project-api-service-value
    dynatrace.com/primary_tags.service-annotation: annotation-project-api-service-value
    metadata.dynatrace.com/primary_tags.service-annotation-metadata: annotation-project-api-service-metadata-value
    metadata.dynatrace.com/primary_tags.source: annotation-project-api-service-value
    primary_tags.service-annotation: annotation-project-api-service-value
spec:
  type: ClusterIP
  selector:
    app: project-api
  ports:
    - port: 80
      targetPort: 5000
---
# project-api-caller Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-api-caller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-api-caller
  template:
    metadata:
      labels:
        app: project-api-caller
        dynatrace.com/pod-project-api-caller-label: label-project-api-caller-pod-value
        metadata.dynatrace.com/pod-project-api-caller-label-metadata: label-project-api-caller-pod-metadata-value
        pod-project-api-caller-label: label-project-api-caller-pod-value
        dynatrace.com/primary_tags.pod-project-api-caller-label: label-project-api-caller-pod-value
        metadata.dynatrace.com/primary_tags.pod-project-api-caller-label-metadata: label-project-api-caller-pod-metadata-value
        primary_tags.pod-project-api-caller-label: label-project-api-caller-pod-value
      annotations:
        dynatrace.com/pod-annotation: annotation-project-api-caller-pod-value
        metadata.dynatrace.com/pod-annotation-metadata: annotation-project-api-caller-pod-metadata-value
        pod-annotation: annotation-project-api-caller-pod-value
        dynatrace.com/primary_tags.pod-annotation: annotation-project-api-caller-pod-value
        metadata.dynatrace.com/primary_tags.pod-annotation-metadata: annotation-project-api-caller-pod-metadata-value
        metadata.dynatrace.com/primary_tags.source: annotation-project-api-caller-pod-value
        primary_tags.pod-annotation: annotation-project-api-caller-pod-value
    spec:
      containers:
        - name: project-api-caller
          image: localhost:32000/test-applications-java-caller:1.0.0
          imagePullPolicy: Always
          env:
            - name: BASE_URL
              value: http://project-api
