FROM alpine:3.21
RUN apk add --no-cache bash curl

WORKDIR /app
COPY call-apis.sh .
RUN chmod +x call-apis.sh

ENV BASE_URL=http://project-api:5000

ENTRYPOINT ["bash", "-c", "exec ./call-apis.sh \"${BASE_URL}\""]
