spring.application.name=project-api
server.port=${APP_PORT:5000}
server.tomcat.threads.max=20

# Logging
logging.level.root=INFO
logging.level.org.springframework.web=WARN
logging.file.path=${APP_LOG_PATH:./logs}
logging.file.name=${APP_LOG_PATH:./logs}/project-api.log

